type Recipe {
  name: String!
  url: String
  lastPreparation: Date
  note: String,
  tags: [String!]
  deleted: Boolean!
}

type Meal {
  date: Date! @unique(index: "uniqueMeal")
  type: MealType!
  recipe: Recipe!
  notes: String
}

enum MealType {
  Lunch,
  Dinner
}

type Query {
  allMeals: [Meal!]
  allRecipes: [Recipe!]
  allRecipesByDeletedFlag(deleted: Boolean!): [Recipe!]
}