type Recipe {
    name: String!
    url: String
    note: String
    tags: [String!]
    deleted: Boolean!
    meals: [Meal!] @relation
}

type Meal {
    date: Date!
    type: MealType!
    recipe: Recipe!
    notes: String
}

enum MealType {
    Lunch
    Dinner
}

type Query {
    allMeals: [Meal!]
    allRecipes: [Recipe!]
    allRecipesByDeletedFlag(deleted: Boolean!): [Recipe!]
    allMealsInDateRange(from: Date!, to: Date!): [Meal!] @resolver(name: "allMealsInDateRange", paginated: true)
}
